name: flutter_finance
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  slang: ^3.31.1
  slang_flutter: ^3.31.0
  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


# dependencies:
#   slang: <version>
#   slang_flutter: <version> # also add this if you use flutter

# dev_dependencies:
#   build_runner: <version> # ONLY if you use build_runner (1/2)
#   slang_build_runner: <version> # ONLY if you use build_runner (2/2)